#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Permettre l'exécution en tant que root
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

# Get application name
application=`getApplication`

echo "Running blockMesh application"
runApplication blockMesh

echo "Running checkMesh application"
runApplication checkMesh

# Décomposition du domaine
echo "Decomposing domain"
runApplication decomposePar

echo "Running potentialFoam application"
runParallel potentialFoam 4

echo "Running viscoelasticFluidFoam solver"
echo "FENE-P model:"
runParallel $application 4

# Reconstruction
echo "Reconstructing solution"
runApplication reconstructPar -latestTime

echo "Running stressDifferences application"
runApplication stressDifferences

echo "Running sample application"
runApplication sample

echo "done!"